name: zam_event_bus_provider
version: 0.5.1
description: A provider for flutter that passes EventBus down to all the widgets.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_event_bus_provider

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  zam_core: ^0.7.0
  zam_event_bus: ^0.9.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  zam_test: ^0.5.0

flutter:
  uses-material-design: true
